config/routes.rb
Rails.application.routes.draw do
  get 'messages/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  devise_for :users

  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create,:destroy]
    resources :book_comments, only: [:create,:destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    # resources :messages, only: [:show, :create]
    get "messages/:id" => "messages#show", as: "message"
    post "messages/:id" => "messages#create", as: "message_post"

    resource :relationships, only: [:create, :destroy]
    get "follow" => "relationships#follow", as: "follow"
    get "followed" => "relationships#followed", as: "followed"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord

  validates :message, presence:true, length:{maximum:140}

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def show
    @user_to = User.find(params[:id])
    @messages = Message.where("(user_id_from=#{params[:user_id]} and user_id_to=#{params[:id]}) or (user_id_to=#{params[:user_id]} and user_id_from=#{params[:id]})")
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    @message.user_id_from = params[:user_id]
    @message.user_id_to = params[:id]
    @message.save
    # redirect_to user_message_path(params[:user_id], params[:id])
  end

  private

  def message_params
    params.require(:message).permit(:message)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/create.js.erb
$("#chatmessage").append('<div class="row shadow"><%= @message.message %></div>')

app/views/messages/show.html.erb
<div class="container" id="chatmessage">
  <h1><%= @user_to.name %>さんとのチャット</h1>
  <% @messages.each do |message| %>
    <div class="<%= ('d-flex justify-content-').concat(message.user_id_from == current_user.id ? 'end':'start') %>" >
      <%= message.message %>
    </div>
  <% end %>
</div>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-9">
      <%= form_with model: @message, url: user_message_post_path(current_user.id, params[:id]) , local:false do |f| %>
        <div class="form-group">
          <%= f.text_field :message, class: 'form-control' %>
        </div>
      <% end %>
    </div>
  </div>
</div>